# Saya menggunakan data F1 DRIVER

##### Import Libary

In [2]:
import numpy as np
import pandas as pd

##### Load Dataset

In [4]:
path = "F1Drivers_Dataset.csv"
df = pd.read_csv(path)

##### Menampilkan 5 Baris Awal Dari Dataset

In [5]:
df.head()

,Driver,Nationality,Seasons,Championships,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,...,Championship Years,Decade,Pole_Rate,Start_Rate,Win_Rate,Podium_Rate,FastLap_Rate,Points_Per_Entry,Years_Active,Champion
0,Carlo Abate,Italy,"[1962, 1963]",0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,NaN,1960,0.0,0.000000,0.0,0.0,0.0,0.000000,2,False
1,George Abecassis,United Kingdom,"[1951, 1952]",0.0,2.0,2.0,0.0,0.0,0.0,0.0,...,NaN,1950,0.0,1.000000,0.0,0.0,0.0,0.000000,2,False
2,Kenny Acheson,United Kingdom,"[1983, 1985]",0.0,10.0,3.0,0.0,0.0,0.0,0.0,...,NaN,1980,0.0,0.300000,0.0,0.0,0.0,0.000000,2,False
3,Andrea de Adamich,Italy,"[1968, 1970, 1971, 1972, 1973]",0.0,36.0,30.0,0.0,0.0,0.0,0.0,...,NaN,1970,0.0,0.833333,0.0,0.0,0.0,0.166667,5,False
4,Philippe Adams,Belgium,[1994],0.0,2.0,2.0,0.0,0.0,0.0,0.0,...,NaN,1990,0.0,1.000000,0.0,0.0,0.0,0.000000,1,False

##### Menampilkan 5 Baris Akir Dari Dataset

In [6]:
df.tail()

,Driver,Nationality,Seasons,Championships,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,...,Championship Years,Decade,Pole_Rate,Start_Rate,Win_Rate,Podium_Rate,FastLap_Rate,Points_Per_Entry,Years_Active,Champion
863,Emilio Zapico,Spain,[1976],0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,1980,0.0,0.000000,0.0,0.0,0.000000,0.000000,1,False
864,Zhou Guanyu,China,[2022],0.0,23.0,23.0,0.0,0.0,0.0,2.0,...,NaN,2020,0.0,1.000000,0.0,0.0,0.086957,0.260870,1,False
865,Ricardo Zonta,Brazil,"[1999, 2000, 2001, 2004, 2005]",0.0,37.0,36.0,0.0,0.0,0.0,0.0,...,NaN,2000,0.0,0.972973,0.0,0.0,0.000000,0.081081,5,False
866,Renzo Zorzi,Italy,"[1975, 1976, 1977]",0.0,7.0,7.0,0.0,0.0,0.0,0.0,...,NaN,1980,0.0,1.000000,0.0,0.0,0.000000,0.142857,3,False
867,Ricardo Zunino,Argentina,"[1979, 1980, 1981]",0.0,11.0,10.0,0.0,0.0,0.0,0.0,...,NaN,1980,0.0,0.909091,0.0,0.0,0.000000,0.000000,3,False

# Menelaah Data

##### Menampilkan Tipe-tipe Data dari setiap kolom

In [8]:
print(df.dtypes)

Driver                 object
Nationality            object
Seasons                object
Championships         float64
Race_Entries          float64
Race_Starts           float64
Pole_Positions        float64
Race_Wins             float64
Podiums               float64
Fastest_Laps          float64
Points                float64
Active                   bool
Championship Years     object
Decade                  int64
Pole_Rate             float64
Start_Rate            float64
Win_Rate              float64
Podium_Rate           float64
FastLap_Rate          float64
Points_Per_Entry      float64
Years_Active            int64
Champion                 bool
dtype: object

In [9]:
df_noid = df.iloc[:,2:]
df_noid

,Seasons,Championships,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,Points,Active,Championship Years,Decade,Pole_Rate,Start_Rate,Win_Rate,Podium_Rate,FastLap_Rate,Points_Per_Entry,Years_Active,Champion
0,"[1962, 1963]",0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,False,NaN,1960,0.0,0.000000,0.0,0.0,0.000000,0.000000,2,False
1,"[1951, 1952]",0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,False,NaN,1950,0.0,1.000000,0.0,0.0,0.000000,0.000000,2,False
2,"[1983, 1985]",0.0,10.0,3.0,0.0,0.0,0.0,0.0,0.0,False,NaN,1980,0.0,0.300000,0.0,0.0,0.000000,0.000000,2,False
3,"[1968, 1970, 1971, 1972, 1973]",0.0,36.0,30.0,0.0,0.0,0.0,0.0,6.0,False,NaN,1970,0.0,0.833333,0.0,0.0,0.000000,0.166667,5,False
4,[1994],0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,False,NaN,1990,0.0,1.000000,0.0,0.0,0.000000,0.000000,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,[1976],0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,False,NaN,1980,0.0,0.000000,0.0,0.0,0.000000,0.000000,1,False
864,[2022],0.0,23.0,23.0,0.0,0.0,0.0,2.0,6.0,True,NaN,2020,0.0,1.000000,0.0,0.0,0.086957,0.260870,1,False
865,"[1999, 2000, 2001, 2004, 2005]",0.0,37.0,36.0,0.0,0.0,0.0,0.0,3.0,False,NaN,2000,0.0,0.972973,0.0,0.0,0.000000,0.081081,5,False
866,"[1975, 1976, 1977]",0.0,7.0,7.0,0.0,0.0,0.0,0.0,1.0,False,NaN,1980,0.0,1.000000,0.0,0.0,0.000000,0.142857,3,False
867,"[1979, 1980, 1981]",0.0,11.0,10.0,0.0,0.0,0.0,0.0,0.0,False,NaN,1980,0.0,0.909091,0.0,0.0,0.000000,0.000000,3,False

##### Menampilkan Statistik Dasar setiap kolom Data yang bertipe Numerik

In [42]:
df_noid = df_noid.select_dtypes(include=['float64', 'int64'])

# fungsi statistik setiap kolom (yang applicable)

In [43]:
df_noid.mean()

Championships          0.084101
Race_Entries          29.917051
Race_Starts           27.694700
Pole_Positions         1.244240
Race_Wins              1.247696
Podiums                3.756912
Fastest_Laps           1.261521
Points                55.849459
Decade              1972.223502
Pole_Rate              0.011471
Start_Rate             0.779824
Win_Rate               0.011050
Podium_Rate            0.041389
FastLap_Rate           0.011894
Points_Per_Entry       0.479158
Years_Active           3.664747
dtype: float64

In [44]:
df_noid.sum()

Championships       7.300000e+01
Race_Entries        2.596800e+04
Race_Starts         2.403900e+04
Pole_Positions      1.080000e+03
Race_Wins           1.083000e+03
Podiums             3.261000e+03
Fastest_Laps        1.095000e+03
Points              4.847733e+04
Decade              1.711890e+06
Pole_Rate           9.956467e+00
Start_Rate          6.768875e+02
Win_Rate            9.591432e+00
Podium_Rate         3.592536e+01
FastLap_Rate        1.032383e+01
Points_Per_Entry    4.159090e+02
Years_Active        3.181000e+03
dtype: float64

In [45]:
df_noid.median()

Championships          0.000000
Race_Entries           7.000000
Race_Starts            5.000000
Pole_Positions         0.000000
Race_Wins              0.000000
Podiums                0.000000
Fastest_Laps           0.000000
Points                 0.000000
Decade              1970.000000
Pole_Rate              0.000000
Start_Rate             0.962251
Win_Rate               0.000000
Podium_Rate            0.000000
FastLap_Rate           0.000000
Points_Per_Entry       0.000000
Years_Active           2.000000
dtype: float64

In [46]:
df_noid.var()

Championships           0.275502
Race_Entries         2892.304530
Race_Starts          2795.921679
Pole_Positions         40.290913
Race_Wins              42.145035
Podiums               208.306469
Fastest_Laps           29.307537
Points              70739.303556
Decade                408.083784
Pole_Rate               0.002166
Start_Rate              0.105172
Win_Rate                0.001899
Podium_Rate             0.011333
FastLap_Rate            0.001893
Points_Per_Entry        1.473372
Years_Active           12.262331
dtype: float64

In [47]:
df_noid.std()

Championships         0.524883
Race_Entries         53.780150
Race_Starts          52.876476
Pole_Positions        6.347512
Race_Wins             6.491921
Podiums              14.432826
Fastest_Laps          5.413644
Points              265.968614
Decade               20.201084
Pole_Rate             0.046544
Start_Rate            0.324303
Win_Rate              0.043579
Podium_Rate           0.106457
FastLap_Rate          0.043514
Points_Per_Entry      1.213826
Years_Active          3.501761
dtype: float64

In [48]:
df_noid.quantile(0.75)

Championships          0.000000
Race_Entries          29.250000
Race_Starts           26.000000
Pole_Positions         0.000000
Race_Wins              0.000000
Podiums                0.000000
Fastest_Laps           0.000000
Points                 8.000000
Decade              1982.500000
Pole_Rate              0.000000
Start_Rate             1.000000
Win_Rate               0.000000
Podium_Rate            0.000000
FastLap_Rate           0.000000
Points_Per_Entry       0.382517
Years_Active           5.000000
Name: 0.75, dtype: float64

# Mencari pencilan dengan Tukey's fences (1)

In [49]:
q1 = df_noid.quantile(0.25)
q3 = df_noid.quantile(0.75)
iqr = q3 - q1
iqr

Championships        0.000000
Race_Entries        27.250000
Race_Starts         25.000000
Pole_Positions       0.000000
Race_Wins            0.000000
Podiums              0.000000
Fastest_Laps         0.000000
Points               8.000000
Decade              22.500000
Pole_Rate            0.000000
Start_Rate           0.333333
Win_Rate             0.000000
Podium_Rate          0.000000
FastLap_Rate         0.000000
Points_Per_Entry     0.382517
Years_Active         4.000000
dtype: float64

# Mencari pencilan dengan Tukey's fences (2)

##### Handle Warning

In [50]:
import warnings 
warnings.filterwarnings('ignore')

##### Outlier Filter

In [51]:
df_noid_align, iqr_new = df_noid.align(iqr, axis=1, copy=False, join='outer')
outlier_filter = (df_noid < q1 - 1.5 * iqr_new) | (df_noid > q3 + 1.5 * iqr_new)
outlier_filter

,Championships,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,Points,Decade,Pole_Rate,Start_Rate,Win_Rate,Podium_Rate,FastLap_Rate,Points_Per_Entry,Years_Active
0,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
864,False,False,False,False,False,False,True,False,True,False,False,False,False,True,False,False
865,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
866,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
867,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

# Mencari pencilan dengan Tukey's fences (3)

In [61]:
df[outlier_filter['Championships']] \
    .loc[:, ['Driver', 'Championships']] \
    .sort_values(by=['Championships'], ascending=False)

                 Driver  Championships
710  Michael Schumacher            7.0
338      Lewis Hamilton            7.0
238  Juan Manuel Fangio            5.0
628         Alain Prost            4.0
812    Sebastian Vettel            4.0
612       Nelson Piquet            3.0
748      Jackie Stewart            3.0
442          Niki Lauda            3.0
107        Jack Brabham            3.0
720        Ayrton Senna            3.0
334       Mika HÃ¤kkinen            2.0
17      Fernando Alonso            2.0
811      Max Verstappen            2.0
169           Jim Clark            2.0
364         Graham Hill            2.0
250  Emerson Fittipaldi            2.0
35       Alberto Ascari            2.0
25       Mario Andretti            1.0
397          Alan Jones            1.0
377          James Hunt            1.0
376         Denny Hulme            1.0
365           Phil Hill            1.0
363          Damon Hill            1.0
351       Mike Hawthorn            1.0
135       Jenson Button            1.0
239         Nino Farina            1.0
670        Nico Rosberg            1.0
669        Keke Rosberg            1.0
657        Jochen Rindt            1.0
635      Kimi RÃ¤ikkÃ¶nen            1.0
489       Nigel Mansell            1.0
698      Jody Scheckter            1.0
759        John Surtees            1.0
814  Jacques Villeneuve            1.0

# Value_counts()

In [63]:
df['Nationality'].value_counts()

Nationality
United Kingdom                164
United States                 160
Italy                          99
France                         72
West Germany                   39
Brazil                         32
Argentina                      25
Switzerland                    24
South Africa                   23
Belgium                        23
Japan                          21
Australia                      18
Netherlands                    16
Austria                        16
Spain                          15
Canada                         15
Germany                        14
Sweden                         11
New Zealand                     9
Finland                         9
Mexico                          6
Portugal                        5
Denmark                         5
Ireland                         5
Rhodesia                        4
Uruguay                         4
Monaco                          4
Russia                          3
East Germany                    3
Colombia                        3
Venezuela                       3
India                           2
Thailand                        2
East Germany, West Germany      1
Hungary                         1
Czech Republic                  1
MonacoÂ Netherlands              1
BelgiumÂ France                  1
Indonesia                       1
Poland                          1
Rhodesia and Nyasaland          1
Morocco                         1
RAF                             1
Liechtenstein                   1
Chile                           1
Malaysia                        1
China                           1
Name: count, dtype: int64

# Analisis Dengan groupby

In [64]:
df.groupby('Nationality')['Points'].std()

Nationality
Argentina                      75.717288
Australia                     381.839144
Austria                       136.100327
Belgium                        45.235353
BelgiumÂ France                       NaN
Brazil                        261.496559
Canada                         78.541951
Chile                                NaN
China                                NaN
Colombia                      177.246533
Czech Republic                       NaN
Denmark                        81.729432
East Germany                    0.000000
East Germany, West Germany           NaN
Finland                       773.551568
France                        120.981550
Germany                       912.079249
Hungary                              NaN
India                           3.535534
Indonesia                            NaN
Ireland                         6.610598
Italy                          52.760007
Japan                          29.050777
Liechtenstein                        NaN
Malaysia                             NaN
Mexico                        490.692334
Monaco                        433.337436
MonacoÂ Netherlands                   NaN
Morocco                              NaN
Netherlands                   508.659553
New Zealand                    95.142364
Poland                               NaN
Portugal                        3.049590
RAF                                  NaN
Rhodesia                        3.000000
Rhodesia and Nyasaland               NaN
Russia                        102.805642
South Africa                   51.324551
Spain                         558.193504
Sweden                         62.369865
Switzerland                    44.067944
Thailand                      137.178716
United Kingdom                365.372992
United States                  21.979514
Uruguay                         0.000000
Venezuela                      43.592813
West Germany                   14.955715
Name: Points, dtype: float64

In [65]:
df.groupby('Nationality')['Points'].mean()

Nationality
Argentina                      25.891200
Australia                     156.527778
Austria                        61.781250
Belgium                        16.652174
BelgiumÂ France                  5.000000
Brazil                        106.718750
Canada                         36.466667
Chile                           3.000000
China                           6.000000
Colombia                      102.333333
Czech Republic                  0.000000
Denmark                        36.800000
East Germany                    0.000000
East Germany, West Germany      0.000000
Finland                       487.944444
France                         47.728750
Germany                       552.464286
Hungary                         1.000000
India                           2.500000
Indonesia                       0.000000
Ireland                         3.200000
Italy                          20.093939
Japan                          12.047619
Liechtenstein                   0.000000
Malaysia                        0.000000
Mexico                        218.833333
Monaco                        218.000000
MonacoÂ Netherlands              0.000000
Morocco                         0.000000
Netherlands                   129.093750
New Zealand                    59.277778
Poland                        274.000000
Portugal                        1.600000
RAF                             0.000000
Rhodesia                        1.500000
Rhodesia and Nyasaland          0.000000
Russia                         89.000000
South Africa                   11.869565
Spain                         196.833333
Sweden                         36.000000
Switzerland                    14.375000
Thailand                      105.000000
United Kingdom                 64.352317
United States                   6.181250
Uruguay                         0.000000
Venezuela                      25.666667
West Germany                    5.435897
Name: Points, dtype: float64

# Korelasi Pearson antara kolom-kolom numerik

In [68]:
df_noid.loc[:,'Race_Entries':].corr()

,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,Points,Decade,Pole_Rate,Start_Rate,Win_Rate,Podium_Rate,FastLap_Rate,Points_Per_Entry,Years_Active
Race_Entries,1.000000,0.996701,0.582264,0.590658,0.757007,0.681107,0.689361,0.498214,0.360392,0.250540,0.391760,0.440430,0.387468,0.636681,0.849973
Race_Starts,0.996701,1.000000,0.591793,0.600889,0.768449,0.691432,0.701817,0.489603,0.367880,0.275386,0.400482,0.451132,0.395277,0.651703,0.844593
Pole_Positions,0.582264,0.591793,1.000000,0.954951,0.901514,0.899697,0.799746,0.181147,0.724572,0.122427,0.702441,0.566939,0.583367,0.713732,0.495873
Race_Wins,0.590658,0.600889,0.954951,1.000000,0.934082,0.931840,0.811054,0.177587,0.641202,0.121174,0.715301,0.574145,0.574646,0.709542,0.503717
Podiums,0.757007,0.768449,0.901514,0.934082,1.000000,0.944862,0.879007,0.242973,0.582819,0.161073,0.646987,0.626834,0.561148,0.784089,0.643342
Fastest_Laps,0.681107,0.691432,0.899697,0.931840,0.944862,1.000000,0.794033,0.213626,0.640768,0.144872,0.691881,0.598409,0.657703,0.718784,0.586038
Points,0.689361,0.701817,0.799746,0.811054,0.879007,0.794033,1.000000,0.305172,0.440628,0.133449,0.480722,0.467058,0.402949,0.857405,0.516597
Decade,0.498214,0.489603,0.181147,0.177587,0.242973,0.213626,0.305172,1.000000,0.033489,0.105855,0.032219,0.007738,0.044675,0.260378,0.230504
Pole_Rate,0.360392,0.367880,0.724572,0.641202,0.582819,0.640768,0.440628,0.033489,1.000000,0.132951,0.790886,0.604504,0.747135,0.561452,0.395762
Start_Rate,0.250540,0.275386,0.122427,0.121174,0.161073,0.144872,0.133449,0.105855,0.132951,1.000000,0.138499,0.207872,0.150043,0.223734,0.290053
Win_Rate,0.391760,0.400482,0.702441,0.715301,0.646987,0.691881,0.480722,0.032219,0.790886,0.138499,1.000000,0.728820,0.868023,0.645480,0.438990
Podium_Rate,0.440430,0.451132,0.566939,0.574145,0.626834,0.598409,0.467058,0.007738,0.604504,0.207872,0.728820,1.000000,0.675740,0.733299,0.510766
FastLap_Rate,0.387468,0.395277,0.583367,0.574646,0.561148,0.657703,0.402949,0.044675,0.747135,0.150043,0.868023,0.675740,1.000000,0.592705,0.445144
Points_Per_Entry,0.636681,0.651703,0.713732,0.709542,0.784089,0.718784,0.857405,0.260378,0.561452,0.223734,0.645480,0.733299,0.592705,1.000000,0.549442
Years_Active,0.849973,0.844593,0.495873,0.503717,0.643342,0.586038,0.516597,0.230504,0.395762,0.290053,0.438990,0.510766,0.445144,0.549442,1.000000